export const placeInfo = [
  {
    id: 1,
    headerTitle: "Phone Store",
    description: "E-commerce website to sell phones",
    img: ".././images/phone-store/1.png",
    img2: ".././images/phone-store/2.png",
    img3: ".././images/phone-store/3.png",
    tools: "Html - Css - Bootstrap - React js - Context api - Paypal api ",
    link: "https://e-commerce-phones-store.netlify.app/",
  },
  {
    id: 2,
    headerTitle: "City Guide App",
    description: "city website that provide information for visitors",
    img: ".././images/city-guide-app/1.png",
    img2: ".././images/city-guide-app/2.png",
    img3: ".././images/city-guide-app/3.png",
    tools: "Html - Css - Bootstrap - React js - Context api - ReactStrap",
    link: "https://my-city-guide.netlify.app/",
  },
  {
    id: 3,
    headerTitle: "shopping-cart",
    description: "Furniture market as a real website",
    img: ".././images/shopping-cart/1.png",
    img2: ".././images/shopping-cart/2.png",
    img3: ".././images/shopping-cart/3.png",
    tools: "Html - Css - Pure JavaScript",
    link: "https://vanilla-js-furniture-market.netlify.app/",
  },
  {
    id: 4,
    headerTitle: "Netflix landing page",
    description: "Landing page for netflix as a real website",
    img: ".././images/netflix/1.png",
    img2: ".././images/netflix/2.png",
    img3: ".././images/netflix/3.png",
    tools: "Html - Css - Pure JavaScript",
    link: "https://landingpage-netflix.netlify.app",
  },
  {
    id: 5,
    headerTitle: "Memoery game",
    description: "simple game using es6 but unfortunately not responsive",
    img: ".././images/memoery-game/1.png",
    img2: ".././images/memoery-game/2.png",
    img3: ".././images/memoery-game/1.png",
    tools: "Html - Css - Bootstrap - React js",
    link: "https://salah330.github.io/MemoryGame-ES6/",
  },
  {
    id: 6,
    headerTitle: "Narrow landing page",
    description: "Landing page for company which sells flowers",
    img: ".././images/narrow/1.png",
    img2: ".././images/narrow/2.png",
    img3: ".././images/narrow/3.png",
    tools: "Html - Css - Pure JavaScript",
    link: "https://narrow-for-flower.netlify.app/",
  },
  {
    id: 7,
    headerTitle: "Convert text to sound ",
    description: "converting text using javascript built in api",
    img: ".././images/text-to-sound/1.png",
    img2: ".././images/text-to-sound/1.png",
    img3: ".././images/text-to-sound/1.png",
    tools: "Html - Css - Pure JavaScript",
    link: "https://convert-text-to-sound.netlify.app/",
  },
  {
    id: 8,
    headerTitle: "Recipes landing page",
    description: "Landing page to fetch recipes and get information",
    img: ".././images/recipes/2.png",
    img2: ".././images/recipes/1.png",
    img3: ".././images/recipes/2.png",
    tools: "Html - Css - React js - Axios",
    link: "https://eat-recipes.netlify.app/",
  },
  {
    id: 9,
    headerTitle: "City Tours landing page",
    description: "Landing page for city tours",
    img: ".././images/city-tours/1.png",
    img2: ".././images/city-tours/1.png",
    img3: ".././images/city-tours/1.png",
    tools: "Html - Css - Bootstrap - React js",
    link: "https://city-tours-reactjs-scss.netlify.app/",
  },
];

export const detailInfo = {
  id: 1,
  headerTitle: "Netflix landing page",
  description: "Landing page for netflix as a real website",
  img: ".././images/netflix/1.png",
  img2: ".././images/netflix/2.png",
  img3: ".././images/netflix/3.png",
  tools: "Html - Css - Pure JavaScript",
  link: "https://landingpage-netflix.netlify.app",
};
